version: "2.4"

services:
  devbox: &devbox
    image: mocoding/ofx
    command: /bin/sh
    build: 
      context: ./
      dockerfile: docker/Dockerfile
    volumes: 
      - .:/app

  test:
    <<: *devbox